#!/usr/bin/env bash
#
# configure-ios.sh — select which capabilities the iOS build ships with.
#
# The switch lives entirely in xcconfig: this script writes (or removes) a small
# untracked overlay that Config/Shared.xcconfig picks up via `#include?`. It never
# touches ios/KumoneIOS.xcodeproj, so toggling CarPlay leaves the tracked Xcode
# project byte-identical and produces no diff to review.
#
# CarPlay is opt-in because `com.apple.developer.carplay-audio` is a restricted
# entitlement: Apple grants it per App ID after a separate CarPlay application.
# Building an unapproved app with it in the entitlements fails to sign with
#   "Entitlement com.apple.developer.carplay-audio not found and could not be
#    included in profile."
# so the default configuration — the one CI and every contributor gets — ships
# neither the entitlement nor the CarPlay scene declaration.
#
# Usage:
#   Scripts/configure-ios.sh            # default build, CarPlay off
#   Scripts/configure-ios.sh --carplay  # CarPlay overlay on
#
# Prefer the Makefile wrappers: `make configure` / `make configure-carplay`.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
IOS_DIR="$REPO_ROOT/ios"
CONFIG_DIR="$IOS_DIR/Config"
GENERATED_DIR="$CONFIG_DIR/Generated"
OVERLAY_XCCONFIG="$CONFIG_DIR/CarPlay.local.xcconfig"

BASE_INFOPLIST="$CONFIG_DIR/Info.plist"
BASE_ENTITLEMENTS="$CONFIG_DIR/KumoneIOS.entitlements"
CARPLAY_INFOPLIST="$GENERATED_DIR/Info-CarPlay.plist"
CARPLAY_ENTITLEMENTS="$GENERATED_DIR/KumoneIOS-CarPlay.entitlements"

PLISTBUDDY=/usr/libexec/PlistBuddy
CARPLAY=0

while [ $# -gt 0 ]; do
  case "$1" in
    --carplay) CARPLAY=1 ;;
    --no-carplay) CARPLAY=0 ;;
    -h|--help) sed -n '2,20p' "${BASH_SOURCE[0]}"; exit 0 ;;
    *) echo "error: unknown argument '$1'" >&2; exit 2 ;;
  esac
  shift
done

# The generated overlay is derived from the checked-in base files on every run, so the
# two never drift apart: edit Config/Info.plist and the CarPlay copy picks the change up
# at the next `make configure-carplay`.
generate_carplay_overlay() {
  mkdir -p "$GENERATED_DIR"

  # --- Info.plist: base + UISupportsCarPlay + the CarPlay template scene ---
  cp "$BASE_INFOPLIST" "$CARPLAY_INFOPLIST"

  # CarPlaySceneDelegate lives in the app target, so the delegate class name must be
  # module-qualified; $(PRODUCT_MODULE_NAME) is expanded by the Info.plist preprocessor
  # at build time.
  "$PLISTBUDDY" \
    -c "Add :UISupportsCarPlay bool true" \
    -c "Add :UIApplicationSceneManifest dict" \
    -c "Add :UIApplicationSceneManifest:UIApplicationSupportsMultipleScenes bool true" \
    -c "Add :UIApplicationSceneManifest:UISceneConfigurations dict" \
    -c "Add :UIApplicationSceneManifest:UISceneConfigurations:CPTemplateApplicationSceneSessionRoleApplication array" \
    -c "Add :UIApplicationSceneManifest:UISceneConfigurations:CPTemplateApplicationSceneSessionRoleApplication:0 dict" \
    -c "Add :UIApplicationSceneManifest:UISceneConfigurations:CPTemplateApplicationSceneSessionRoleApplication:0:UISceneConfigurationName string CarPlay" \
    -c "Add :UIApplicationSceneManifest:UISceneConfigurations:CPTemplateApplicationSceneSessionRoleApplication:0:UISceneClassName string CPTemplateApplicationScene" \
    -c "Add :UIApplicationSceneManifest:UISceneConfigurations:CPTemplateApplicationSceneSessionRoleApplication:0:UISceneDelegateClassName string \$(PRODUCT_MODULE_NAME).CarPlaySceneDelegate" \
    "$CARPLAY_INFOPLIST" >/dev/null

  # --- Entitlements: base + the CarPlay audio entitlement ---
  cp "$BASE_ENTITLEMENTS" "$CARPLAY_ENTITLEMENTS"
  "$PLISTBUDDY" \
    -c "Add :com.apple.developer.carplay-audio bool true" \
    "$CARPLAY_ENTITLEMENTS" >/dev/null

  # --- The xcconfig overlay that repoints the build at both generated files ---
  cat > "$OVERLAY_XCCONFIG" <<'EOF'
// CarPlay.local.xcconfig — GENERATED by Scripts/configure-ios.sh --carplay.
// Not tracked by git. Delete it (or run `make configure`) to return to a
// default, CarPlay-free build.
KUMONE_INFOPLIST_FILE = Config/Generated/Info-CarPlay.plist
KUMONE_ENTITLEMENTS_FILE = Config/Generated/KumoneIOS-CarPlay.entitlements
EOF
}

if [ "$CARPLAY" -eq 1 ]; then
  generate_carplay_overlay
else
  rm -f "$OVERLAY_XCCONFIG"
  rm -rf "$GENERATED_DIR"
fi

if [ "$CARPLAY" -eq 1 ]; then
  cat <<'EOF'
✅ Configured KumoneIOS with CarPlay ENABLED.

Signing this build needs the CarPlay (Audio) capability on your App ID:
  1. Enable CarPlay (Audio) for the App ID at
     https://developer.apple.com/account/resources/identifiers/list
     (requires an approved CarPlay request: https://developer.apple.com/carplay/)
  2. Regenerate / re-download the provisioning profile
  3. Build and run on a device, then connect to CarPlay or the CarPlay Simulator
     (Xcode ▸ Open Developer Tool ▸ Simulator, I/O ▸ External Displays ▸ CarPlay)

Run `make configure` to switch back to a CarPlay-free build.
EOF
else
  echo "✅ Configured KumoneIOS (default: CarPlay disabled)."
fi
